FROM golang:alpine as builder

RUN apk update && apk upgrade && apk add --no-cache git

RUN mkdir /app

WORKDIR /app

ENV GO111MODILE=on

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o service_vessel
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o service_vessel *.go

# Run container
FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir /app
WORKDIR /app

COPY --from=builder /app/service_vessel .

CMD ["./service_vessel"]
