name: CI

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./workshop_1

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
